name: testing and building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    pipeline:
        runs_on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout Commit
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
                with:
                  node-version: [ 16. x , 18. x ] 
            - name: install modules
              run: npm i
            - name: build prodaction project
              run: npm run build:prod
            - name: unit testing
              run: npm run test
